import os
import sys

# Script that updates the TOC, List of Figures, and List of Tables page numbers in generate_elaborate_report.py

with open('generate_elaborate_report.py', 'r', encoding='utf-8') as f:
    code = f.read()

# Replace TOC table mapping with exact page mapping for ~70-80 page doc
old_toc = '''    toc_data = [
        ["Title Page", "i"],
        ["Declaration by Candidate", "ii"],
        ["Bonafide Certificate", "iii"],
        ["Abstract", "iv"],
        ["Acknowledgements", "v"],
        ["Table of Contents", "vi"],
        ["List of Figures", "x"],
        ["List of Tables", "xii"],
        ["List of Symbols, Abbreviations and Nomenclature", "xiii"],
        ["", ""],
        ["CHAPTER 1: INTRODUCTION & BACKGROUND", "1"],
        ["  1.1 Background and Domain Overview", "1"],
        ["  1.2 Intrusion Detection in High-Throughput Networks", "3"],
        ["  1.3 Threat Landscape and Attack Vectors in Modern Enterprise Subnets", "5"],
        ["  1.4 Limitations of Signature and Traditional Machine Learning IDS", "8"],
        ["  1.5 Graph Neural Networks in Cybersecurity: Opportunities and Vulnerabilities", "11"],
        ["  1.6 Vulnerabilities to Adversarial Perturbations & Dynamic Topology", "13"],
        ["  1.7 Problem Statement", "15"],
        ["  1.8 Research Objectives & Key Contributions", "16"],
        ["  1.9 Organization of the Thesis Report", "17"],
        ["", ""],
        ["CHAPTER 2: LITERATURE REVIEW & RELATED WORK", "18"],
        ["  2.1 Historical Evolution of Network Anomaly Detection (1987-2025)", "18"],
        ["  2.2 Comparative Analysis of Shallow ML vs Deep Sequential Models", "21"],
        ["  2.3 Graph Neural Networks in Network Security (GCN, GAT, Dynamic Graphs)", "24"],
        ["  2.4 Multi-Agent Systems & Distributed Consensus Protocols", "27"],
        ["  2.5 Adaptive Trust Evaluation, Reputation Metrics & Sybil Defense", "30"],
        ["  2.6 Explainable AI (XAI) & Threat Knowledge Graph Mapping", "32"],
        ["  2.7 Literature Gap Analysis & Summary Table", "34"],
        ["", ""],
        ["CHAPTER 3: SYSTEM ARCHITECTURE & METHODOLOGY (ATGC-MACIDS)", "36"],
        ["  3.1 Overview of the ATGC-MACIDS Paradigm", "36"],
        ["  3.2 Dynamic Network Graph Construction & Temporal Graph Snapshots", "39"],
        ["  3.3 Multi-Agent Architecture & Local Perception Nodes", "42"],
        ["  3.4 Deep Temporal GNN Encoder (ST-GAT Architecture)", "44"],
        ["  3.5 Adaptive Trust Evaluation Engine & Dynamic Reputation Scoring", "48"],
        ["  3.6 Jacobi Consensus Protocol & Distributed Vector Agreement", "51"],
        ["  3.7 Optimization Objective & Dual Loss Functions", "54"],
        ["  3.8 MITRE ATT&CK Threat Knowledge Graph Mapping Engine", "56"],
        ["  3.9 System Implementation & Algorithmic Pseudocode", "57"],
        ["", ""],
        ["CHAPTER 4: EXPERIMENTAL EVALUATION & RESULTS", "59"],
        ["  4.1 Benchmark Dataset Characterization (UNSW-NB15)", "59"],
        ["  4.2 Data Preprocessing, Scaling & Graph Snapshot Partitioning", "62"],
        ["  4.3 Experimental Setup, Hardware/Software Infrastructure & Hyperparameters", "64"],
        ["  4.4 Baseline Models for Comparative Evaluation", "66"],
        ["  4.5 Quantitative Evaluation: Detection Accuracy & Metrics", "67"],
        ["  4.6 Robustness Analysis Against Adversarial Graph Attacks & Sybil Nodes", "71"],
        ["  4.7 Latency, Scalability, and Consensus Iteration Convergence Analysis", "73"],
        ["  4.8 Ablation Studies (ST-GAT, Trust Engine, Consensus Layers)", "75"],
        ["", ""],
        ["CHAPTER 5: DISCUSSION, THREAT EXPLAINABILITY & SYSTEM DEPLOYMENT", "77"],
        ["  5.1 In-Depth Analysis of Experimental Findings", "77"],
        ["  5.2 Model Interpretability via Feature Saliency & Node Attribution", "79"],
        ["  5.3 Automated Mapping of Detected Anomalies to MITRE ATT&CK TTPs", "81"],
        ["  5.4 Enterprise SIEM Integration, Real-Time Dashboard Architecture", "83"],
        ["  5.5 Operational Security & Deployment Considerations", "85"],
        ["", ""],
        ["CHAPTER 6: CONCLUSION & FUTURE WORK", "87"],
        ["  6.1 Summary of Research Contributions", "87"],
        ["  6.2 Key Empirical Takeaways", "88"],
        ["  6.3 Limitations of the Current Study", "89"],
        ["  6.4 Directions for Future Research", "90"],
        ["", ""],
        ["APPENDICES", "91"],
        ["  Appendix A: Mathematical Proofs & Convergence Analysis", "91"],
        ["  Appendix B: Core Algorithmic Code Implementation Listings", "94"],
        ["  Appendix C: UNSW-NB15 Dataset Feature Definitions & Schemas", "97"],
        ["", ""],
        ["REFERENCES (IEEE Citation Format)", "99"]
    ]'''

new_toc = '''    toc_data = [
        ["Title Page", "i"],
        ["Declaration by Candidate", "ii"],
        ["Bonafide Certificate", "iii"],
        ["Abstract", "iv"],
        ["Acknowledgements", "v"],
        ["Table of Contents", "vi"],
        ["List of Figures", "x"],
        ["List of Tables", "xii"],
        ["List of Symbols, Abbreviations and Nomenclature", "xiii"],
        ["", ""],
        ["CHAPTER 1: INTRODUCTION & BACKGROUND", "1"],
        ["  1.1 Background and Domain Overview", "1"],
        ["  1.2 Intrusion Detection in High-Throughput Networks", "3"],
        ["  1.3 Threat Landscape and Attack Vectors in Modern Enterprise Subnets", "5"],
        ["  1.4 Limitations of Signature and Traditional Machine Learning IDS", "7"],
        ["  1.5 Graph Neural Networks in Cybersecurity: Opportunities and Vulnerabilities", "9"],
        ["  1.6 Vulnerabilities to Adversarial Perturbations & Dynamic Topology", "11"],
        ["  1.7 Problem Statement", "12"],
        ["  1.8 Research Objectives & Key Contributions", "13"],
        ["  1.9 Organization of the Thesis Report", "14"],
        ["", ""],
        ["CHAPTER 2: LITERATURE REVIEW & RELATED WORK", "15"],
        ["  2.1 Historical Evolution of Network Anomaly Detection (1987-2025)", "15"],
        ["  2.2 Comparative Analysis of Shallow ML vs Deep Sequential Models", "18"],
        ["  2.3 Graph Neural Networks in Network Security (GCN, GAT, Dynamic Graphs)", "20"],
        ["  2.4 Multi-Agent Systems & Distributed Consensus Protocols", "23"],
        ["  2.5 Adaptive Trust Evaluation, Reputation Metrics & Sybil Defense", "25"],
        ["  2.6 Explainable AI (XAI) & Threat Knowledge Graph Mapping", "27"],
        ["  2.7 Literature Gap Analysis & Summary Table", "28"],
        ["", ""],
        ["CHAPTER 3: SYSTEM ARCHITECTURE & METHODOLOGY (ATGC-MACIDS)", "30"],
        ["  3.1 Overview of the ATGC-MACIDS Paradigm", "30"],
        ["  3.2 Dynamic Network Graph Construction & Temporal Graph Snapshots", "32"],
        ["  3.3 Multi-Agent Architecture & Local Perception Nodes", "35"],
        ["  3.4 Deep Temporal GNN Encoder (ST-GAT Architecture)", "37"],
        ["  3.5 Adaptive Trust Evaluation Engine & Dynamic Reputation Scoring", "40"],
        ["  3.6 Jacobi Consensus Protocol & Distributed Vector Agreement", "42"],
        ["  3.7 Optimization Objective & Dual Loss Functions", "44"],
        ["  3.8 MITRE ATT&CK Threat Knowledge Graph Mapping Engine", "45"],
        ["  3.9 System Implementation & Algorithmic Pseudocode", "46"],
        ["", ""],
        ["CHAPTER 4: EXPERIMENTAL EVALUATION & RESULTS", "48"],
        ["  4.1 Benchmark Dataset Characterization (UNSW-NB15)", "48"],
        ["  4.2 Data Preprocessing, Scaling & Graph Snapshot Partitioning", "50"],
        ["  4.3 Experimental Setup, Hardware/Software Infrastructure & Hyperparameters", "52"],
        ["  4.4 Baseline Models for Comparative Evaluation", "53"],
        ["  4.5 Quantitative Evaluation: Detection Accuracy & Metrics", "54"],
        ["  4.6 Robustness Analysis Against Adversarial Graph Attacks & Sybil Nodes", "57"],
        ["  4.7 Latency, Scalability, and Consensus Iteration Convergence Analysis", "59"],
        ["  4.8 Ablation Studies (ST-GAT, Trust Engine, Consensus Layers)", "60"],
        ["", ""],
        ["CHAPTER 5: DISCUSSION, THREAT EXPLAINABILITY & SYSTEM DEPLOYMENT", "62"],
        ["  5.1 In-Depth Analysis of Experimental Findings", "62"],
        ["  5.2 Model Interpretability via Feature Saliency & Node Attribution", "64"],
        ["  5.3 Automated Mapping of Detected Anomalies to MITRE ATT&CK TTPs", "66"],
        ["  5.4 Enterprise SIEM Integration, Real-Time Dashboard Architecture", "68"],
        ["  5.5 Operational Security & Deployment Considerations", "70"],
        ["", ""],
        ["CHAPTER 6: CONCLUSION & FUTURE WORK", "71"],
        ["  6.1 Summary of Research Contributions", "71"],
        ["  6.2 Key Empirical Takeaways", "72"],
        ["  6.3 Limitations of the Current Study", "73"],
        ["  6.4 Directions for Future Research", "74"],
        ["", ""],
        ["APPENDICES", "75"],
        ["  Appendix A: Mathematical Proofs & Convergence Analysis", "75"],
        ["  Appendix B: Core Algorithmic Code Implementation Listings", "77"],
        ["  Appendix C: UNSW-NB15 Dataset Feature Definitions & Schemas", "79"],
        ["", ""],
        ["REFERENCES (IEEE Citation Format)", "81"]
    ]'''

old_fig = '''    fig_data = [
        ["Figure 3.1", "High-Level System Architecture of the ATGC-MACIDS Framework", "37"],
        ["Figure 3.2", "Spatio-Temporal Graph Attention Network (ST-GAT) Encoder Architecture", "45"],
        ["Figure 3.3", "Adaptive Trust Evaluation Engine & Dynamic Peer Reputation Scoring Workflow", "49"],
        ["Figure 4.1", "Training & Validation Loss / Accuracy Curves over 15 Epochs on UNSW-NB15", "68"],
        ["Figure 4.2", "Confusion Matrix of Multi-Class Intrusion Detection Performance", "69"],
        ["Figure 4.3", "Receiver Operating Characteristic (ROC) and Precision-Recall Curves", "70"],
        ["Figure 4.4", "Comparative Benchmark Performance across Baseline Models", "71"],
        ["Figure 4.5", "Detection Accuracy under Increasing Ratio of Compromised Adversarial Nodes", "72"],
        ["Figure 4.6", "Jacobi Consensus Vector Residual Error Convergence across Iterations", "74"],
        ["Figure 5.1", "Global Feature Saliency and SHAP Feature Attribution Ranking", "80"],
        ["Figure 5.2", "Cyber Threat Knowledge Graph (CT-KG) Mapped to MITRE ATT&CK Matrix", "82"],
        ["Figure 5.3", "Interactive Enterprise Web Dashboard & Real-Time SIEM Monitoring Interface", "84"]
    ]'''

new_fig = '''    fig_data = [
        ["Figure 3.1", "High-Level System Architecture of the ATGC-MACIDS Framework", "31"],
        ["Figure 3.2", "Spatio-Temporal Graph Attention Network (ST-GAT) Encoder Architecture", "38"],
        ["Figure 3.3", "Adaptive Trust Evaluation Engine & Dynamic Peer Reputation Scoring Workflow", "41"],
        ["Figure 4.1", "Training & Validation Loss / Accuracy Curves over 15 Epochs on UNSW-NB15", "55"],
        ["Figure 4.2", "Confusion Matrix of Multi-Class Intrusion Detection Performance", "55"],
        ["Figure 4.3", "Receiver Operating Characteristic (ROC) and Precision-Recall Curves", "56"],
        ["Figure 4.4", "Comparative Benchmark Performance across Baseline Models", "56"],
        ["Figure 4.5", "Detection Accuracy under Increasing Ratio of Compromised Adversarial Nodes", "58"],
        ["Figure 4.6", "Jacobi Consensus Vector Residual Error Convergence across Iterations", "59"],
        ["Figure 5.1", "Global Feature Saliency and SHAP Feature Attribution Ranking", "65"],
        ["Figure 5.2", "Cyber Threat Knowledge Graph (CT-KG) Mapped to MITRE ATT&CK Matrix", "67"],
        ["Figure 5.3", "Interactive Enterprise Web Dashboard & Real-Time SIEM Monitoring Interface", "69"]
    ]'''

old_tbl = '''    tbl_list_data = [
        ["Table 2.1", "Comprehensive Literature Comparison Matrix of NIDS Paradigms", "35"],
        ["Table 3.1", "Dynamic Graph Mathematical Notations and Variable Definitions", "40"],
        ["Table 3.2", "Spatio-Temporal Graph Attention Network (ST-GAT) Hyperparameters", "46"],
        ["Table 4.1", "UNSW-NB15 Dataset Traffic Distribution across 9 Attack Categories", "60"],
        ["Table 4.2", "Hardware & Software Experimental Execution Environment", "65"],
        ["Table 4.3", "Quantitative Performance Benchmark of Baseline vs. ATGC-MACIDS", "68"],
        ["Table 4.4", "Per-Category Intrusion Detection Metrics on UNSW-NB15 Test Partition", "70"],
        ["Table 4.5", "Ablation Study of ATGC-MACIDS Architectural Components", "76"],
        ["Table C.1", "Complete Feature Schema and Description of UNSW-NB15 Telemetry", "97"]
    ]'''

new_tbl = '''    tbl_list_data = [
        ["Table 2.1", "Comprehensive Literature Comparison Matrix of NIDS Paradigms", "29"],
        ["Table 3.1", "Dynamic Graph Mathematical Notations and Variable Definitions", "33"],
        ["Table 3.2", "Spatio-Temporal Graph Attention Network (ST-GAT) Hyperparameters", "39"],
        ["Table 4.1", "UNSW-NB15 Dataset Traffic Distribution across 9 Attack Categories", "49"],
        ["Table 4.2", "Hardware & Software Experimental Execution Environment", "52"],
        ["Table 4.3", "Quantitative Performance Benchmark of Baseline vs. ATGC-MACIDS", "54"],
        ["Table 4.4", "Per-Category Intrusion Detection Metrics on UNSW-NB15 Test Partition", "56"],
        ["Table 4.5", "Ablation Study of ATGC-MACIDS Architectural Components", "61"],
        ["Table C.1", "Complete Feature Schema and Description of UNSW-NB15 Telemetry", "80"]
    ]'''

code = code.replace(old_toc, new_toc)
code = code.replace(old_fig, new_fig)
code = code.replace(old_tbl, new_tbl)

with open('generate_elaborate_report.py', 'w', encoding='utf-8') as f:
    f.write(code)

print("Updated TOC, List of Figures, and List of Tables page numbers in generate_elaborate_report.py!")
